---
theme: dataone
title: DataONE
baseURL: https://dataone.org
languageCode: en-us
metaDataFormat: yaml
pygmentsCodeFences: true
enableEmoji: true
pagination:
  pagerSize: 10
markup:
  highlight:
    codeFences: true
    style: monokailight
    lineNos: true
    lineNumbersInTable: false
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
enableRobotsTXT: true
publishDir: docs
permalinks:
  about: "/:filename"
  community: "/:filename"
  learning: "/:filename"
  services: "/:filename"
  features: "/:filename"
  news: "/:section/:filename"
  people: "/:section/:filename"
  webinars: "/webinars/:slug"
  meetings: "/meetings/:filename"
