footer:
  - name: Services
    weight: 1
  - name: Community
    weight: 2
  - name: Learning
    weight: 3
  - name: About
    weight: 4
  - url: https://dataoneorg.github.io/Education/
    name: Skillbuilding
    title: Skillbuilding Hub
    parent: Learning
    pre: award
    weight: 3
  - url: metrics
    name: Metrics
    parent: About
    title: Summary of Holdings
    weight: 1.5
  - name: Find Data
    pre: search
    url: https://search.dataone.org/data
    weight: 5
secondary_nav:
- name: Get DataONE Plus
  title: Get DataONE Plus
  pre: "d1-plus-logo"
  weight: 1
  url: /plus/
  post: DataONE Plus Ad
- name: Donate
  title: Donate
  weight: 2
  url: donate
- name: Sign-in
  title: Sign-in
  weight: 3
  url: signin
  pre: user
- name: Profile
  weight: 4
  pre: user
- name: My profile
  parent: Profile
  weight: 1
  pre: user-check
  url: "SEARCH/profile/USERNAME"
- name: My groups
  parent: Profile
  weight: 2
  pre: users
  url: "SEARCH/profile/USERNAME/s=settings/s=groups"
- name: My datasets
  parent: Profile
  weight: 3
  pre: file-text
  url: "SEARCH/data/my-data"
- name: My portals
  parent: Profile
  weight: 4
  pre: star
  url: SEARCH/profile/USERNAME/s=settings/s=portals
- name: Sign out
  parent: Profile
  weight: 100
  url: SEARCH/signout
primary_nav:
- name: Data
  weight: 1
- name: Services
  weight: 2
- name: Community
  weight: 3
- name: Learning
  weight: 4
- name: About
  weight: 5
- url: https://dataoneorg.github.io/Education/
  name: Skillbuilding
  title: Skillbuilding Hub
  parent: Learning
  pre: award
  weight: 3
- url: metrics
  name: Metrics
  parent: About
  title: Summary of Holdings
  pre: bar-chart-2
  weight: 1.5
- name: Find data
  weight: 1
  url: https://search.dataone.org/data
  title: Find data
  parent: Data
  pre: search
- name: Portals
  weight: 2
  url: https://search.dataone.org/portals
  title: Portals
  parent: Data
  pre: star
