---
theme: dataone
title: DataONE
languageCode: en-us
metaDataFormat: yaml
pygmentsCodeFences: true
paginate: 9
markup:
  highlight:
    codeFences: true
    style: monokailight
    lineNos: true
    lineNumbersInTable: false
enableEmoji: true
enableRobotsTXT: true
publishDir: docs
permalinks:
  posts: "/:filename/"
  pages: "/:filename/"
DisqusShortname: "x"
params:
  description: DataONE's products and services.
  footerText: 'DataONE is a collaboration among many partner organizations, and is
    funded by the US National Science Foundation (NSF) under a Cooperative Agreement.
    Acknowledgement: This material is based upon work supported by the National Science
    Foundation under Grant Numbers 0830944 and 1430508. Disclaimer: Any opinions,
    findings, and conclusions or recommendations expressed in this material are those
    of the author(s) and do not necessarily reflect the views of the National Science
    Foundation.'
  contactLink: /about/contact/
  donateLink: https://giving.ucsb.edu/Funds/Give?id=353
  joinFormId: join-form
  blockDir: themes/dataone/layouts/partials/blocks/
  mobileDesktopBreakpoint: 640
  dateFormat: "January 2, 2006"
  dateFormatShort: "2 Jan 2006"
  datetimeFormat: "January 2, 2006 15:04 MST"
  datetimeFormatShort: "2 Jan 2006 15:04 MST"
  zoom:
    phone_numbers:
      - city: "New York, USA"
        number: "+1 646 558 8656"
      - city: "San Jose, USA"
        number: "+1 408 638 0968"
    URL_local_number: "https://us04web.zoom.us/u/fcD9Evl80t"
  mailingAddress:
    delivery_points:
    - "735 State St #300"
    city: "Santa Barbara"
    administrative_area: "California"
    postal_code: "93101"
    country: "United States"
    longitude: ""
    latitude: ""
  social:
    vimeo: "https://vimeo.com/channels/dataone"
    youtube: "https://www.youtube.com/user/DataONEorg"
    twitter: "https://twitter.com/DataONEorg"
menu:
  footer:
  - url: https://dataoneorg.github.io/Education/
    name: Skillbuilding Hub
    title: Skillbuilding Hub
    weight: 7
  - url: https://www.dataone.org/
    name: Archived content
    title: Old DataONE website
    weight: 12
  toplevel:
  - url: https://dataoneorg.github.io/Education/
    name: Skillbuilding Hub
    title: Skillbuilding Hub
    parent: Resources
    name: Skillbuilding
    weight: 3
  - name: Organization
    weight: 4
  - name: Resources
    weight: 3
  - name: Network
    weight: 2
