---
theme: dataone
title: DataONE
languageCode: en-us
metaDataFormat: yaml
pygmentsCodeFences: true
enableEmoji: true
paginate: 10
markup:
  highlight:
    codeFences: true
    style: monokailight
    lineNos: true
    lineNumbersInTable: false
  goldmark:
    renderer:
      unsafe: true
enableEmoji: true
enableRobotsTXT: true
publishDir: docs
permalinks:
  about: "/:filename"
  resources: "/:filename"
  network: "/:filename"
  services: "/:filename"
  features: "/:filename"
  news: "/:section/:filename"
  people: "/:section/:title"
  webinars: "/webinars/:slug"
params:
  description: DataONE's products and services.
  footerText: 'DataONE is a collaboration among many partner organizations, and is
    funded by the US National Science Foundation (NSF) under a Cooperative Agreement.
    Acknowledgement: This material is based upon work supported by the National Science
    Foundation under Grant Numbers 0830944 and 1430508. Disclaimer: Any opinions,
    findings, and conclusions or recommendations expressed in this material are those
    of the author(s) and do not necessarily reflect the views of the National Science
    Foundation.'
  links:
    contact: "/contact/"
    donate: https://giving.ucsb.edu/Funds/Give?id=353
    signin: https://search.dataone.org/signin
    old_website: https://www.dataone.org
  joinFormId: join-form
  blockDir: themes/dataone/layouts/partials/blocks/
  mobileDesktopBreakpoint: 699
  dateFormat:
    default: January 2, 2006
    short: 2 Jan 2006
    time: January 2, 2006 15:04 MST
    time_short: 2 Jan 2006 15:04 MST
  contact:
    email: support@dataone.org
    slack: "https://slack.dataone.org"
    address:
      delivery_points:
      - '735 State St #300'
      city: Santa Barbara
      administrative_area: California
      postal_code: '93101'
      country: United States
      longitude: ''
      latitude: ''
  social:
    vimeo: https://vimeo.com/channels/dataone
    twitter: https://twitter.com/DataONEorg
menu:
  footer:
  - url: https://dataoneorg.github.io/Education/
    name: Skillbuilding Hub
    title: Skillbuilding Hub
    weight: 8
  - url: https://www.dataone.org/
    name: Archived content
    title: Old DataONE website
    weight: 14
  secondary_nav:
  - name: Get DataONE Plus
    title: Get DataONE Plus
    pre: "d1-plus-logo"
    weight: 1
    url: /plus/
    post: DataONE Plus Ad
  - name: Donate
    title: Donate
    weight: 2
    url: donate
  - name: Sign-in
    title: Sign-in
    weight: 3
    url: signin
  primary_nav:
  - name: Find Data
    pre: search
    url: https://search.dataone.org/data
    weight: 1
  - name: Services
    weight: 2
  - name: Network
    weight: 3
  - name: Community
    weight: 4
  - name: About
    weight: 5
  - url: https://dataoneorg.github.io/Education/
    name: Skillbuilding
    title: Skillbuilding Hub
    parent: Community
    pre: award
    weight: 3
