# This is a basic workflow to help you get started with Actions

name: Build MetacatUI Export

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.82.0"
          extended: true
      - name: Build Site
        run: |
            echo "Building production site"
            npm install
            hugo -d ./build --minify --cleanDestinationDir
            
      - name: Checkout MetacatUI
        uses: actions/checkout@v3
        with:
          repository: NCEAS/metacatui
          ref: develop

      - name: Commit to MetacatUI

